# Generated by Django 4.2.6 on 2023-10-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='blogmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.blogmodel'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='blogModel',
            field=models.ManyToManyField(to='blogApp.blogmodel'),
        ),
    ]
