# Generated by Django 4.2.6 on 2023-10-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='uuidfield',
            new_name='uuid',
        ),
    ]
