# Generated by Django 4.2.6 on 2023-10-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_blogmodel_created_at_blogmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='pub_date',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='featured_image',
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogApp.blogmodel')),
            ],
        ),
    ]
