# Generated by Django 4.2.6 on 2023-10-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_rename_uuidfield_blogmodel_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='uuid',
        ),
    ]
