# Generated by Django 4.2.6 on 2023-10-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_blogimage_blogmodel_alter_tag_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='blogmodel',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='blogModel',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blogImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogApp.blogimage'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='blogApp.tag'),
        ),
    ]
